### ISSUE TITLE
newsbeuter fails to install 10.5/G5

### ISSUE THREAD

**Issue by ghost** [mistydemeo/tigerbrew#147]
brew install newsbeuter                                                                                   ~
==> Downloading http://newsbeuter.org/downloads/newsbeuter-2.7.tar.gz
###### ################################################################## 100.0%

==> make
You can download ncurses5.4 from here: 

One or more dependencies couldn't be found. Please install
these packages and retry compilation.
make: **\* [config.mk] Error 1

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting

/usr/local/Library/Homebrew/utils.rb:276:in `open': Failed to connect to: https://api.github.com/legacy/issues/search/mistydemeo/tiger/open/newsbeuter (GitHub::Error)
certificate verify failed
    from /usr/local/Library/Homebrew/utils.rb:281:in`each_issue_matching'
    from /usr/local/Library/Homebrew/utils.rb:293:in `issues_for_formula'
    from /usr/local/Library/Homebrew/exceptions.rb:178:in`issues'
    from /usr/local/Library/Homebrew/exceptions.rb:212:in `dump'
    from /usr/local/Library/brew.rb:112

https://gist.github.com/7703107

**Comment by breakeven** [comment]
@mistydemeo I cannot figure out how to make this thing find my ncurses. Is it possible that we need a homebrew/version for 5.4 specifically, to make this work?
