### ISSUE TITLE
Qt fails to install G5/10.5

### ISSUE THREAD

**Issue by breakeven** [mistydemeo/tigerbrew#148]
==> Downloading http://download.qt-project.org/official_releases/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar
######################################################################## 100.0%
==> ./configure -prefix /usr/local/Cellar/qt/4.8.5 -system-zlib -confirm-license -opensource -nomake demos -nomake e
==> make
platform/graphics/IntRect.h:38: error: ‘NSRect’ has a previous declaration as ‘typedef struct CGRect NSRect’
make[3]: *** [.obj/release-shared/PluginViewMac.o] Error 1
make[2]: *** [release] Error 2
make[1]: *** [sub-WebCore-make_default-ordered] Error 2
make: *** [sub-webkit-make_default-ordered] Error 2

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting

/usr/local/Library/Homebrew/utils.rb:276:in `open': Failed to connect to: https://api.github.com/legacy/issues/search/mistydemeo/tiger/open/qt (GitHub::Error)
certificate verify failed
	from /usr/local/Library/Homebrew/utils.rb:281:in `each_issue_matching'
	from /usr/local/Library/Homebrew/utils.rb:293:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:178:in `issues'
	from /usr/local/Library/Homebrew/ex

https://gist.github.com/7718403
https://gist.github.com/7718409

**Comment by breakeven** [comment]
No longer relevant I guess
