### ISSUE TITLE
Strange error: "Suspicious Installation Failure"

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#181]
I got a strange error today on Tiger PPC while trying to build a custom formula that builds fine on Leo PPC (and Homebrew):

````
 brew install -d ./hgexp.rb
/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /Users/gmn/.rc/scripts/hmb/max/hgexp.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/xz.rb
/usr/lib/ruby/1.8/irb/input-method.rb:87:in `include': wrong argument type Class (expected Module) (TypeError)
        from /usr/lib/ruby/1.8/irb/input-method.rb:87
        from /usr/lib/ruby/1.8/irb.rb:20:in `require'
        from /usr/lib/ruby/1.8/irb.rb:20
        from /usr/local/Library/Homebrew/debrew/irb.rb:1:in `require'
        from /usr/local/Library/Homebrew/debrew/irb.rb:1
        from /usr/local/Library/Homebrew/debrew.rb:12:in `require'
        from /usr/local/Library/Homebrew/debrew.rb:12
        from /usr/local/Library/Homebrew/build.rb:17:in `require'
        from /usr/local/Library/Homebrew/build.rb:17
Error: Suspicious installation failure
/usr/local/Library/Homebrew/formula_installer.rb:519:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:512:in `ignore_interrupts'
/usr/local/Library/Homebrew/formula_installer.rb:512:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:198:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:105:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:99:in `send'
/usr/local/Library/brew.rb:99
````

I dunno why `irb` is involved in this, either.

Let me know if you want to see the formula.  Basically all it does is `make` and `make PREFIX=somewhereoutsidethecellar install`.

**Comment by chdiza** [comment]
I'm no longer having this problem as far as I can tell.

**Comment by mistydemeo** [comment]
Glad to hear it!
