### ISSUE TITLE
Error: undefined method `mktmpdir' for Dir:Class

### ISSUE THREAD

**Issue by antoine2711** [mistydemeo/tigerbrew#324]
**Error: undefined method `mktmpdir' for Dir:Class**
I was asked to: *Please report this bug*…

```
smtp2:bin admin$ brew install git
==> Installing dependencies for git: xz, pkg-config, makedepend, openssl, curl-ca-bundle, curl
==> Installing git dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.1.tar.gz
Error: undefined method `mktmpdir' for Dir:Class
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/extend/fileutils.rb:11:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:879:in `stage'
/usr/local/Library/Homebrew/formula.rb:511:in `brew'
/usr/local/Library/Homebrew/build.rb:106:in `install'
/usr/local/Library/Homebrew/build.rb:178
```

```
smtp2:bin admin$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Git could not be found in your PATH.
Tigerbrew uses Git for several internal functions, and some formulae use Git
checkouts instead of stable tarballs. You may want to install Git:
  brew install git

Warning: Your XQuartz (2.1.6) is outdated
Please install XQuartz 2.6.3:
  https://xquartz.macosforge.org
smtp2:bin admin$ brew update
You must: brew install git
Error: Failure while executing: git init
```

```
smtp2:bin admin$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4e
OS X: 10.5.8-Power Macintosh
Xcode: 3.1.4
CLT: N/A
GCC-4.0: build 5493
GCC-4.2: build 5577
LLVM-GCC: build 2064
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 1.8.6-369
Perl: /usr/bin/perl
Python: /usr/bin/python => /System/Library/Frameworks/Python.framework/Versions/2.5/bin/python2.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.5.0_30
```

**Comment by mistydemeo** [comment]
Should be fixed now.

**Comment by antoine2711** [comment]
```brew install git```
Still gives me the same error. Should I update something before? (Tried ```brew doctor```).

**Comment by mistydemeo** [comment]
Can you try `brew update` first, then retry?

**Comment by antoine2711** [comment]
Tried. 
```
smtp2:Users admin$ brew update
You must: brew install git
Error: Failure while executing: git init
```

**Comment by mistydemeo** [comment]
Oh, of course! And you can't install git because... heh.

Okay, try this. I just uploaded Leopard binaries of the software you need; you can't run `brew update`, but you can install from URL. Run these three commands in order:

```
brew install https://raw.githubusercontent.com/mistydemeo/tigerbrew/master/Library/Formula/openssl.rb
brew install https://raw.githubusercontent.com/mistydemeo/tigerbrew/master/Library/Formula/curl-ca-bundle.rb
brew install https://raw.githubusercontent.com/mistydemeo/tigerbrew/master/Library/Formula/curl.rb
brew install https://raw.githubusercontent.com/mistydemeo/tigerbrew/master/Library/Formula/git.rb
```

You should have git installed by the end of it, in which case you can `brew update` and install other things.

**Comment by antoine2711** [comment]
Hi Misty,

   Thanks for your great support, it did it. 

   Just for your information, after your 4 installs, (plus an update of ca-cert), I executed ```brew doctor```, and I've got those 2 warnings.

```
Warning: "config" scripts exist outside your system or Tigerbrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Tigerbrew if the config script overrides a system or Tigerbrew provided
script of the same name. We found the following "config" scripts:

  /opt/local/bin/ncurses5-config
  /opt/local/bin/ncursesw5-config
```

**Comment by mistydemeo** [comment]
It looks like you have an install of ncurses from some other source - possibly Macports?

It's okay to ignore this warning for now, but it'll be useful to diagnose if something goes wrong.

**Comment by antoine2711** [comment]
Yes, I did also play with MacPorts.

Keep up the good work and thanks again.

2015-05-05 12:58 GMT-04:00 Misty De Meo <notifications@github.com>:
