### ISSUE TITLE
brew search fails on OS X 10.5.8 (PowerPC)

### ISSUE THREAD

**Issue by miniupnp** [mistydemeo/tigerbrew#355]
```
$ brew search
Error: undefined method `reduce' for #<Array:0x8dedc>
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/utils.rb:271:in `puts_columns'
/usr/local/Library/Homebrew/cmd/search.rb:29:in `search'
/usr/local/Library/brew.rb:121:in `send'
/usr/local/Library/brew.rb:121
```
https://gist.github.com/miniupnp/e71e53587efcb9caa724

**Comment by mistydemeo** [comment]
Should be fixed, do you mind retrying?

**Comment by miniupnp** [comment]
indeed, it works now. thanks for the quick fix !

**Comment by mistydemeo** [comment]
No problem!
