### ISSUE TITLE
Tkinter not working on Mac OS 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#454]
After installing python like this: 'brew install python --with-tcl-tk", I tried a very simple program for Tkinter. It didn't work. Here is the call to Tk() and the error message:

>>> from Tkinter import *
>>> root = Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.12_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

The correct version of Tk is being used. This is how I checked it:
>>> from Tkinter import *
>>> TkVersion
8.6

**Comment by programmingkidx** [comment]
Found out I have to run Python thru X11 in order for Tkinter to work :( 

Not cool.

**Comment by sevan** [comment]
Unfortunately the OS X gui support in TCL/TK requires 10.6 at least, so we opt for X11 support on older OS X releases just to get things working.
