### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by maxwellb** [mistydemeo/tigerbrew#472]
Received the following error when running `brew update`. It may be noted that I have not run the command in likely over a year. `brew upgrade` is currently running, so far without issue.

```text
Mon Apr  3 21:56:43 EDT 2017 :: ~
$ brew update
Checking out files: 100% (3046/3046), done.
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formulary.rb:262:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:135:in `send'
/usr/local/Library/brew.rb:135
```

**Comment by maxwellb** [comment]
D'oh. Currently reading wiki/troubleshooting. Will close if I was an idiot, or confirm once complete.

**Comment by maxwellb** [comment]
Didn't follow instructions, this isn't even formatted correctly. Sorry.

**Comment by mistydemeo** [comment]
That's fine, no worries! Did you get it working?
