### ISSUE TITLE
gcc5 failed to install under Tiger / iMac G3

### ISSUE THREAD

**Issue by mmolinac** [mistydemeo/tigerbrew#538]
Hi!
I just tried to install gcc5 with brew, as:

`brew install gcc5`

and also with:

`brew install gcc5 --cc=gcc-4.2`

with the following output / error:

```
==> Downloading https://ftpmirror.gnu.org/gcc/gcc-5.4.0/gcc-5.4.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/gcc5-5.4.0.tar.bz2
==> Patching
patching file gcc/jit/Make-lang.in
==> ../configure --build=powerpc-apple-darwin8.11.0 --prefix=/usr/local/Cellar/gcc5/5.4.0 --libdir=/usr/local/Cellar/gcc5/5.4.0/lib/gcc/5 --enab
==> make bootstrap

Last 15 lines from /Users/manuelmc/Library/Logs/Homebrew/gcc5/02.make:
/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/xg++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc5/5.4.0/powerpc-apple-darwin8.11.0/bin/ -nostdinc++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include/powerpc-apple-darwin8.11.0  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs -c   -g -O2 -mdynamic-no-pic  -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl014/include -I/usr/local/opt/cctools/include -I/usr/local/opt/isl014/include -F/usr/local/Frameworks -o gimple-fold.o -MT gimple-fold.o -MMD -MP -MF ./.deps/gimple-fold.TPo ../../gcc/gimple-fold.c
/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/xg++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc5/5.4.0/powerpc-apple-darwin8.11.0/bin/ -nostdinc++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include/powerpc-apple-darwin8.11.0  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs -c   -g -O2 -mdynamic-no-pic  -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -I. -I../../gcc -I../../gcc/. -I../../gcc/../include -I../../gcc/../libcpp/include -I/usr/local/opt/gmp/include -I/usr/local/opt/mpfr/include -I/usr/local/opt/libmpc/include  -I../../gcc/../libdecnumber -I../../gcc/../libdecnumber/dpd -I../libdecnumber -I../../gcc/../libbacktrace -I/usr/local/opt/isl014/include -I/usr/local/opt/cctools/include -I/usr/local/opt/isl014/include -F/usr/local/Frameworks -o gimple-low.o -MT gimple-low.o -MMD -MP -MF ./.deps/gimple-low.TPo ../../gcc/gimple-low.c
/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/xg++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc5/5.4.0/powerpc-apple-darwin8.11.0/bin/ -nostdinc++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include/powerpc-apple-darwin8.11.0  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs -c   -g -O2 -mdynamic-no-pic  -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -I. -Ibuild -I../../gcc -I../../gcc/build -I../../gcc/../include  -I../../gcc/../libcpp/include -I/usr/local/opt/cctools/include -I/usr/local/opt/isl014/include -F/usr/local/Frameworks \
        -o build/genmatch.o ../../gcc/genmatch.c
/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/xg++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc5/5.4.0/powerpc-apple-darwin8.11.0/bin/ -nostdinc++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include/powerpc-apple-darwin8.11.0  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs -c   -g -O2 -mdynamic-no-pic  -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -I. -Ibuild -I../../gcc -I../../gcc/build -I../../gcc/../include  -I../../gcc/../libcpp/include -I/usr/local/opt/cctools/include -I/usr/local/opt/isl014/include -F/usr/local/Frameworks \
        -o build/hash-table.o ../../gcc/hash-table.c
/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/xg++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/./prev-gcc/ -B/usr/local/Cellar/gcc5/5.4.0/powerpc-apple-darwin8.11.0/bin/ -nostdinc++ -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -B/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include/powerpc-apple-darwin8.11.0  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/include  -I/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/libstdc++-v3/libsupc++ -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -L/private/tmp/gcc520171118-458-1b9p5yw/gcc-5.4.0/build/prev-powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs   -g -O2 -mdynamic-no-pic  -gtoggle -DIN_GCC    -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -DGENERATOR_FILE -static-libstdc++ -static-libgcc  -o build/genmatch \
    build/genmatch.o ../libcpp/libcpp.a ../libiberty/libiberty.a build/errors.o build/vec.o build/hash-table.o .././libiberty/libiberty.a  -liconv
build/genmatch --gimple ../../gcc/match.pd \
    > tmp-gimple-match.c
dyld: incompatible cpu-subtype
make[3]: *** [s-match] Error 133
make[2]: *** [all-stage2-gcc] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [bootstrap] Error 2

READ THIS: https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
```

My configuration is the following (iMac G3, Mac OS Tiger 10.4.11 with all patches):

```
$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 405110641660fb4e6aee3dfcbdf3484b4f0497e4
Last commit: 5 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: single-core 32-bit g3
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
GCC-4.2: build 5553
Clang: N/A
X11: 1.1.3 => /usr/X11R6
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_3/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /Users/manuelmc
Java: N/A
```

Sadly, I was not able to execute 'gist-logs' to attach it to the issue:

```
$ brew gist-logs gcc5
Error: undefined method `ord' for 226:Fixnum
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/vendor/okjson.rb:506:in `ucharcopy'
/usr/local/Library/Homebrew/vendor/okjson.rb:478:in `strenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:77:in `valenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `objenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `map'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `each'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `map'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `objenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:75:in `valenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `objenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `map'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `each'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `map'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `objenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:75:in `valenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `objenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `map'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `each'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `map'
/usr/local/Library/Homebrew/vendor/okjson.rb:428:in `objenc'
/usr/local/Library/Homebrew/vendor/okjson.rb:65:in `encode'
/usr/local/Library/Homebrew/utils/json.rb:16:in `dump'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:108:in `make_request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:113:in `post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:72:in `create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:24:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:140:in `gist_logs'
/usr/local/Library/brew.rb:143:in `send'
/usr/local/Library/brew.rb:143
```

Regards,

**Comment by mistydemeo** [comment]
```
build/genmatch --gimple ../../gcc/match.pd \
    > tmp-gimple-match.c
dyld: incompatible cpu-subtype
make[3]: *** [s-match] Error 133
make[2]: *** [all-stage2-gcc] Error 2
make[1]: *** [stage2-bubble] Error 2
make: *** [bootstrap] Error 2
```

Hmmm, that's interesting... I wonder if it's related to your being on a G3? Would you be able to upload the files from `~/Library/Logs/Homebrew/gcc` please?

**Comment by mmolinac** [comment]
Yes, of course.

[gcc5_brew_logs.tar.gz](https://github.com/mistydemeo/tigerbrew/files/1488846/gcc5_brew_logs.tar.gz)

I have to say that on my iBook G4 this same package works like a charm.

**Comment by mistydemeo** [comment]
Thanks! Looks like we're sending GCC the correct flags to get a G3 build, but this implies that somewhere in the chain, something was built in an incompatible way. To check if it was one of the dependencies or GCC itself, can you show me the output of:

```
otool -h /usr/local/opt/gmp/lib/libgmp.dylib /usr/local/opt/gmp/lib/libgmpxx.dylib /usr/local/opt/libmpc/lib/libmpc.dylib /usr/local/opt/mpfr/lib/libmpfr.dylib /usr/local/opt/isl/lib/libisl.dylib
```

**Comment by mmolinac** [comment]
Of course! Here's the output:

```
$ otool -h /usr/local/opt/gmp/lib/libgmp.dylib /usr/local/opt/gmp/lib/libgmpxx.dylib /usr/local/opt/libmpc/lib/libmpc.dylib /usr/local/opt/mpfr/lib/libmpfr.dylib /usr/local/opt/isl/lib/libisl.dylib
/usr/local/opt/gmp/lib/libgmp.dylib:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          9          6     9       1332 0x00000085
/usr/local/opt/gmp/lib/libgmpxx.dylib:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          9          6    12       1756 0x00002085
/usr/local/opt/libmpc/lib/libmpc.dylib:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          9          6    11       1036 0x00002085
/usr/local/opt/mpfr/lib/libmpfr.dylib:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          9          6    10       1320 0x00000085
otool: can't open file: /usr/local/opt/isl/lib/libisl.dylib (No such file or directory)
```
I tried to find the last file by other means:

```
$ otool -h /usr/local/opt/isl01*/lib/libisl.dylib
/usr/local/opt/isl011/lib/libisl.dylib:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          9          6    10       1136 0x00002085
/usr/local/opt/isl014/lib/libisl.dylib:
Mach header
      magic cputype cpusubtype   filetype ncmds sizeofcmds      flags
 0xfeedface      18          9          6    10       1264 0x00002085
```

Hope that it helps.

**Comment by mistydemeo** [comment]
OK, that looks fine. `cpusubtype 9` is `CPU_SUBTYPE_POWERPC_750`, e.g. G3, so your dependencies are fine. The failure is happening within the GCC build.

**Comment by mistydemeo** [comment]
Got shell access to a G3 Mac running Tiger, so I can start debugging this. Sorry for the holdup!

**Comment by mmolinac** [comment]
BTW it you need help, I have mine over here, and I'm available to do tests.

**Comment by mistydemeo** [comment]
> BTW if you need help, I have mine over here, and I'm available to do tests.

If you're able to give me SSH access, that would be very helpful. Unfortunately this only repros on G3s, and I don't have one of those myself.

**Comment by mmolinac** [comment]
Give me some time to arrange it. I'll keep you posted.

**Comment by mmolinac** [comment]
Arranged. I've sent you credentials through email.

**Comment by mistydemeo** [comment]
Think I'm starting to get somewhere.

It looks like almost everything was built with cputype 18 (CPU_TYPE_POWERPC) and cpusubtype 0 (CPU_SUBTYPE_POWERPC_ALL), which is expected. libgcc was built with cpusubtype 9 (CPU_SUBTYPE_POWERPC_750), which is fair enough, that’s what we’re building on. However, libstdc++ was built with cpusubtype 10 (CPU_SUBTYPE_POWERPC_7400) - oops! dyld's message about an incompatible CPU subtype was on the money.

I'm not yet sure why it's happening - the logs indicate that we're passing `-mcpu=750` when building/linking `libstdc++`, which should result in a build for the correct arch. I haven't ruled out a compiler bug or a linker bug.

I've tested this by running `brew install gcc -d` and dropping into a shell when it fails; I then used `otool -h` on the objects and the dynamic/static libraries being linked in the step that failed to take a look at the mach header and determine the cpusubtype. It returns a number, but that can be looked up in `/usr/include/mach/machine.h`.

Luckily modern versions of OS X still have support for this older mach stuff, so you can copy a failed build directory to a modern machine and look at it there. Since I'm sshing into G3s, that's what I've been doing.

**Comment by mistydemeo** [comment]
Made some progress, but it's not quite there.

e111e5345ee8905a4aca46083ed4c855c63886f7 fixed the cpusubtype issue, allowing linking against the built libstdc++ to succeed; with that, the build got a *lot* further. After about ~36 hours, I hit a new error in stage 3:

```
make "DESTDIR=" "RPATH_ENVVAR=DYLD_LIBRARY_PATH" "TARGET_SUBDIR=powerpc-apple-darwin8.11.0" "bindir=/usr/local/Cellar/gcc/7.2.0/bin" "datadir=/usr/local/Cellar/gcc/7.2.0/share" "exec_prefix=/usr/local/Cellar/gcc/7.2.0" "includedir=/usr/local/Cellar/gcc/7.2.0/include" "datarootdir=/usr/local/Cellar/gcc/7.2.0/share" "docdir=/usr/local/Cellar/gcc/7.2.0/share/doc/" "infodir=/usr/local/Cellar/gcc/7.2.0/share/info" "pdfdir=/usr/local/Cellar/gcc/7.2.0/share/doc/" "htmldir=/usr/local/Cellar/gcc/7.2.0/share/doc/" "libdir=/usr/local/Cellar/gcc/7.2.0/lib/gcc/7" "libexecdir=/usr/local/Cellar/gcc/7.2.0/libexec" "lispdir=" "localstatedir=/usr/local/Cellar/gcc/7.2.0/var" "mandir=/usr/local/Cellar/gcc/7.2.0/share/man" "oldincludedir=/usr/include" "prefix=/usr/local/Cellar/gcc/7.2.0" "sbindir=/usr/local/Cellar/gcc/7.2.0/sbin" "sharedstatedir=/usr/local/Cellar/gcc/7.2.0/com" "sysconfdir=/usr/local/Cellar/gcc/7.2.0/etc" "tooldir=/usr/local/Cellar/gcc/7.2.0/powerpc-apple-darwin8.11.0" "build_tooldir=/usr/local/Cellar/gcc/7.2.0/powerpc-apple-darwin8.11.0" "target_alias=powerpc-apple-darwin8.11.0" "AWK=awk" "BISON=bison" "CC_FOR_BUILD=/usr/local/bin/gcc-4.2" "CFLAGS_FOR_BUILD=-Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "CXX_FOR_BUILD=/usr/local/bin/g++-4.2 -std=gnu++98" "EXPECT=expect" "FLEX=flex" "INSTALL=/usr/bin/install -c" "INSTALL_DATA=/usr/bin/install -c -m 644" "INSTALL_PROGRAM=/usr/bin/install -c" "INSTALL_SCRIPT=/usr/bin/install -c" "LDFLAGS_FOR_BUILD=-L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names" "LEX=flex" "M4=gm4" "MAKE=make" "RUNTEST=runtest" "RUNTESTFLAGS=" "SED=/usr/bin/sed" "SHELL=/bin/sh" "YACC=bison -y" "`echo 'ADAFLAGS=' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "ADA_CFLAGS=" "AR_FLAGS=rc" "`echo 'BOOT_ADAFLAGS=-gnatpg' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "BOOT_CFLAGS=-g -O2 -mdynamic-no-pic" "BOOT_LDFLAGS=" "CFLAGS=-Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "CXXFLAGS=-Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "LDFLAGS=-L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names" "LIBCFLAGS=-Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "LIBCXXFLAGS=-Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL -fno-implicit-templates" "STAGE1_CHECKING=--enable-checking=yes" "STAGE1_LANGUAGES=c,c++,lto" "GNATBIND=no" "GNATMAKE=no" "AR_FOR_TARGET=ar" "AS_FOR_TARGET=/usr/local/Cellar/cctools/806/bin/as" "CC_FOR_TARGET=/private/tmp/gcc20180109-29968-1905ms5/gcc-7.2.0/build/./gcc/xgcc -B/private/tmp/gcc20180109-29968-1905ms5/gcc-7.2.0/build/./gcc/" "CFLAGS_FOR_TARGET=-g -O2 -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "CPPFLAGS_FOR_TARGET=" "CXXFLAGS_FOR_TARGET=-g -O2 -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "DLLTOOL_FOR_TARGET=dlltool" "FLAGS_FOR_TARGET=-B/usr/local/Cellar/gcc/7.2.0/powerpc-apple-darwin8.11.0/bin/ -B/usr/local/Cellar/gcc/7.2.0/powerpc-apple-darwin8.11.0/lib/ -isystem /usr/local/Cellar/gcc/7.2.0/powerpc-apple-darwin8.11.0/include -isystem /usr/local/Cellar/gcc/7.2.0/powerpc-apple-darwin8.11.0/sys-include" "GFORTRAN_FOR_TARGET=/private/tmp/gcc20180109-29968-1905ms5/gcc-7.2.0/build/./gcc/gfortran -B/private/tmp/gcc20180109-29968-1905ms5/gcc-7.2.0/build/./gcc/" "GOC_FOR_TARGET=" "GOCFLAGS_FOR_TARGET=-O2 -g" "LD_FOR_TARGET=ld" "LIPO_FOR_TARGET=lipo" "LDFLAGS_FOR_TARGET=" "LIBCFLAGS_FOR_TARGET=-g -O2 -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL" "LIBCXXFLAGS_FOR_TARGET=-g -O2 -Os -w -pipe -mcpu=750 -faltivec -mmacosx-version-min=10.4 -force_cpusubtype_ALL -fno-implicit-templates" "NM_FOR_TARGET=nm" "OBJDUMP_FOR_TARGET=objdump" "OBJCOPY_FOR_TARGET=" "RANLIB_FOR_TARGET=ranlib" "READELF_FOR_TARGET=readelf" "STRIP_FOR_TARGET=strip" "WINDRES_FOR_TARGET=windres" "WINDMC_FOR_TARGET=windmc" "BUILD_CONFIG=bootstrap-debug" "`echo 'LANGUAGES=' | sed -e s'/[^=][^=]*=$/XFOO=/'`" "LEAN=false" "STAGE1_CFLAGS=-g -mdynamic-no-pic" "STAGE1_CXXFLAGS=-g -mdynamic-no-pic" "STAGE1_TFLAGS=" "STAGE2_CFLAGS=-g -O2 -mdynamic-no-pic  -gtoggle" "STAGE2_CXXFLAGS=-g -O2 -mdynamic-no-pic  -gtoggle" "STAGE2_TFLAGS=" "STAGE3_CFLAGS=-g -O2 -mdynamic-no-pic " "STAGE3_CXXFLAGS=-g -O2 -mdynamic-no-pic " "STAGE3_TFLAGS=" "STAGE4_CFLAGS=-g -O2 -mdynamic-no-pic " "STAGE4_CXXFLAGS=-g -O2 -mdynamic-no-pic " "STAGE4_TFLAGS=" "STAGEprofile_CFLAGS=-g -O2 -mdynamic-no-pic  -gtoggle -fprofile-generate" "STAGEprofile_CXXFLAGS=-g -O2 -mdynamic-no-pic  -gtoggle -fprofile-generate" "STAGEprofile_TFLAGS=" "STAGEfeedback_CFLAGS=-g -O2 -mdynamic-no-pic  -fprofile-use" "STAGEfeedback_CXXFLAGS=-g -O2 -mdynamic-no-pic  -fprofile-use" "STAGEfeedback_TFLAGS=" "STAGEautoprofile_CFLAGS=-g -O2 -mdynamic-no-pic  -gtoggle -g" "STAGEautoprofile_CXXFLAGS=-g -O2 -mdynamic-no-pic  -gtoggle -g" "STAGEautoprofile_TFLAGS=" "STAGEautofeedback_CFLAGS=-g -O2 -mdynamic-no-pic " "STAGEautofeedback_CXXFLAGS=-g -O2 -mdynamic-no-pic " "STAGEautofeedback_TFLAGS=" "CXX_FOR_TARGET= $r/./gcc/xg++ -B$r/./gcc/ -nostdinc++ `if test -f $r/powerpc-apple-darwin8.11.0/libstdc++-v3/scripts/testsuite_flags; then /bin/sh $r/powerpc-apple-darwin8.11.0/libstdc++-v3/scripts/testsuite_flags --build-includes; else echo -funconfigured-libstdc++-v3 ; fi` -L$r/powerpc-apple-darwin8.11.0/libstdc++-v3/src -L$r/powerpc-apple-darwin8.11.0/libstdc++-v3/src/.libs -L$r/powerpc-apple-darwin8.11.0/libstdc++-v3/libsupc++/.libs" "TFLAGS=" "CONFIG_SHELL=/bin/sh" "MAKEINFO=makeinfo --split-size=5000000 --split-size=5000000"  compare
mv: rename prev-fixincludes to stage2-fixincludes: No such file or directory
rm -f stage_current
Comparing stages 2 and 3
warning: gcc/cc1obj-checksum.o differs
warning: gcc/cc1objplus-checksum.o differs
Comparison successful.
if false; then \
  rm -rf stage2-*; \
  echo timestamp >  stage2-lean; \
fi
mv: rename stage2-fixincludes to prev-fixincludes: No such file or directory
```

Full logs: https://gist.github.com/mistydemeo/f28d570d4a5b3cbd444cadc7e14f37eb

**Comment by mistydemeo** [comment]
Success!

```
/usr/local/Cellar/gcc/7.2.0: 884 files, 168M, built in 1553.2 minutes
```

I'm going to add support for using this gcc-7 to #549, then merge that branch. I'll follow up with a backport of the G3 patch to the other GCCs in a second PR.

**Comment by EricFromCanada** [comment]
Ran into the same `rename stage2-fixincludes` issue while test-compiling the updated gcc5 formula on a G3. Can that be fixed in the formula or does it need manual intervention each time?

**Comment by mistydemeo** [comment]
@EricFromCanada Do you mind opening a new issue with logs? There may be other changes I need to apply to `gcc5`. The formula I know works is `gcc`, which installs 7.2.0.
