### ISSUE TITLE
How do you uninstall tigerbrew? no script?

### ISSUE THREAD

**Issue by chaseholden** [mistydemeo/tigerbrew#646]
Immediately upon installing on a macOS El Capitan (10.11), I experienced the following errors so I just want to remove tiger brew but surprisingly, there is no documentation or commands for this?

Thanks,
Chase

tiger brew > brew doctor
Warning: Broken symlinks were found. Remove them with `brew prune`:
    /usr/local/share/fish/vendor_completions.d/brew.fish
    /usr/local/share/man/man1/README.md
Error: /usr/local/Library/Formula/coreutils.rb:73: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Library/Formula/coreutils.rb:76: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Library/Formula/coreutils.rb:76: syntax error, unexpected ':', expecting keyword_end
/usr/local/Library/Formula/coreutils.rb:77: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Library/Formula/coreutils.rb:78: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Library/Formula/coreutils.rb:78: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Library/Formula/coreutils.rb:79: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Library/Formula/coreutils.rb:79: syntax error, unexpected ':', expecting keyword_end
/usr/local/Library/Formula/coreutils.rb:80: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Library/Homebrew/cmd/doctor.rb:1102:in `check_for_non_prefixed_coreutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:1277:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `doctor'
/usr/local/Library/brew.rb:143:in `<main>'

**Comment by tree-s** [comment]
I beleive that you can do the following:

[How do I uninstall Homebrew?](https://github.com/mistydemeo/tigerbrew/blob/master/share/doc/homebrew/FAQ.md#how-do-i-uninstall-homebrew)

**Comment by sevan** [comment]
In case anyone digs this up in the future:
`/usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby -e "$(/usr/local/opt/curl/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/d8aeae7efb14ed9e4f7934b4782f04d5305562cc/uninstall)"` should do the trick, see issue #1459 for history.
