### ISSUE TITLE
iPerf app - Tigerbrew issue

### ISSUE THREAD

**Issue by mateusz-piotrowski** [mistydemeo/tigerbrew#668]
I use PowerMac10.2 with processor PowerPC G4 (1.2).

I want install iPerf but I can't do it because probably I have issue with homebrew core.

`Mac-mini:~ matt$ brew search iperf
Error: /usr/local/Library/Taps/homebrew/homebrew-core/Formula/iperf.rb:24: syntax error, unexpected keyword_ensure, expecting keyword_end
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:168:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Library/Homebrew/cmd/search.rb:144:in `block in search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:143:in `map'
/usr/local/Library/Homebrew/cmd/search.rb:143:in `search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:44:in `search'
/usr/local/Library/brew.rb:143:in `<main>'
Mac-mini:~ matt$ `

**Comment by mateusz-piotrowski** [comment]
Did you had time and possibility to check my request?
