### ISSUE TITLE
`brew doctor` script format failure on fresh install on macOS 10.9

### ISSUE THREAD

**Issue by RandomInsano** [mistydemeo/tigerbrew#710]
Just trying Tigerbrew before I go trying to find install media for macOS 10.13 here. Hit a problem on a fresh install:

```
$ brew doctor
Error: /usr/local/Library/Formula/coreutils.rb:73: syntax error, unexpected <<
  def caveats; <<~EOS
                 ^
/usr/local/Library/Formula/coreutils.rb:76: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    can add a "gnubin" directory to your PATH from your bashrc like:
                                ^
/usr/local/Library/Formula/coreutils.rb:76: syntax error, unexpected ':', expecting keyword_end
/usr/local/Library/Formula/coreutils.rb:77: dynamic constant assignment
        PATH="#{opt_libexec}/gnubin:$PATH"
             ^
/usr/local/Library/Formula/coreutils.rb:78: dynamic constant assignment
    Additionally, you can access their man pag...
                 ^
/usr/local/Library/Formula/coreutils.rb:78: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
    Additionally, you can access their man pages with ...
                         ^
/usr/local/Library/Formula/coreutils.rb:79: syntax error, unexpected tIDENTIFIER, expecting keyword_end
    the "gnuman" directory to your MANPATH from your bashrc as well:
                          ^
/usr/local/Library/Formula/coreutils.rb:79: syntax error, unexpected ':', expecting keyword_end
/usr/local/Library/Formula/coreutils.rb:80: dynamic constant assignment
        MANPATH="#{opt_libexec}/gnuman:$MANPATH"
                ^
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Library/Homebrew/cmd/doctor.rb:1102:in `check_for_non_prefixed_coreutils'
/usr/local/Library/Homebrew/cmd/doctor.rb:1277:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `doctor'
/usr/local/Library/brew.rb:143:in `<main>'
```

Output of `brew --config`:
```
$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew
HEAD: 7d810af7e0badb02ce3aa34d4603f4651b1966e6
Last commit: 7 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: 8-core 64-bit sandybridge
OS X: 10.9.5-x86_64
Curl: /usr/bin/curl
Xcode: N/A
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.0.0-481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
```

I installed the command line tools before any of this like so:

```
$ xcrun
$ xcode-select --install # Chose to just install the command line tools here
```

That's about it.

**Comment by mistydemeo** [comment]
Aha. I think I know what's going on here.

Tigerbrew provides a newer copy of Ruby that should be installed to help deal with this, but it looks like it's not being installed/used for you. Some of the files in Tigerbrew use Ruby 2.3+ syntax, which your system Ruby can't parse. There is an Intel build: https://github.com/mistydemeo/tigerbrew/blob/master/Library/Homebrew/cmd/vendor-install.sh#L19-L23

Looks like the Ruby helper currently believes that Ruby 2.0 or later is new enough, which is clearly not true: https://github.com/mistydemeo/tigerbrew/blob/c23d064d465d029e782a9e782d2892812dae388c/Library/Homebrew/utils/ruby.sh#L44-L54

I'll look at fixing this.

**Comment by mistydemeo** [comment]
Should be fixed now. Mind testing again after running `brew update`?

**Comment by RandomInsano** [comment]
No problem! Looks like I get a new error but I'll cut a new ticket for this one.
