### ISSUE TITLE
undefined method `license' for Formulary (on OS X 10.9.5)

### ISSUE THREAD

**Issue by precabal** [mistydemeo/tigerbrew#711]
Hi, I'm trying to install a formula from `zackelia/formulae`. The tap goes fine, but when I run `brew install bclm`, I get the following:
```
Error: undefined method `license' for Formulary::FormulaNamespace47e6584fc4c5f4402e6cc98dc9969ee8::Bclm:Class
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Homebrew/Library/Taps/zackelia/homebrew-formulae/Formula/bclm.rb:7:in `<class:Bclm>'
/usr/local/Homebrew/Library/Taps/zackelia/homebrew-formulae/Formula/bclm.rb:1:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:356:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Homebrew/Library/brew.rb:143:in `<main>'
```

(On Mavericks)

**Comment by precabal** [comment]
sorry, will repost following guidelines.
