### ISSUE TITLE
Python Idle3 won't open under 10.5.8ppc

### ISSUE THREAD

**Issue by smnbldwn** [mistydemeo/tigerbrew#730]
I installed Python 3.7.0 using homebrew as it is more up to date than the version offered by python.org. It seems to work fine in the terminal but if I try to open idle3 it crashes. I already installed python 2.7.15 in the same way and idle opens up fine.
$ idle3
Traceback (most recent call last):
  File "/usr/local/bin/idle3", line 3, in <module>
    from idlelib.pyshell import main
  File "/usr/local/Cellar/python3/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/idlelib/pyshell.py", line 30, in <module>
    parent=root)
  File "/usr/local/Cellar/python3/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/messagebox.py", line 91, in showerror
    return _show(title, message, ERROR, OK, **options)
  File "/usr/local/Cellar/python3/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/messagebox.py", line 72, in _show
    res = Message(**options).show()
  File "/usr/local/Cellar/python3/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/commondialog.py", line 43, in show
    s = w.tk.call(self.command, *w._options(self.options))
_tkinter.TclError

The output from brew doctor is :

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libfuse.0.dylib
    /usr/local/lib/libulockmgr.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/ulockmgr.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libulockmgr.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Tigerbrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfuse.a
    /usr/local/lib/libulockmgr.a

Is there anything I should be doing?

**Comment by smnbldwn** [comment]
Sorry I couldn't format the terminal output as code for some reason on TenFourFox.

**Comment by smnbldwn** [comment]
Output from brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 888006523fedbaec21ca5c305825214bcf3622ea
Last commit: 9 weeks ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: single-core 32-bit g4e
OS X: 10.5.8-Power Macintosh
Curl: /usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: 3.1.4
CLT: N/A
GCC-4.0: build 5493
GCC-4.2: build 5577
LLVM-GCC: build 2064
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 2.3.3-222 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.15/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.5.0_30-b03

**Comment by sevan** [comment]
Did you build python3 `--with-tcl-tk`?
