### ISSUE TITLE
php failed to build on 10.9.5

### ISSUE THREAD

**Issue by BaxterZZZ** [mistydemeo/tigerbrew#777]
My actual goal is to get php 5.4 or 5.5 or something in the 5 range to work with TLS 1.2 on my mac running 10.9.5 mavericks. I was able to install tigerbrew. From there I installed wget and that brought in OpenSSL 1.0.2j that supports TLS 1.2 and I updated the expired root certificates for Let's Encrypt. Then curl could connect with a test site via TLS 1.2, but php still used TLS 1. So, I wanted to install a new php built to use OpenSSL.

I tried these fairly recent instructions and none of the taps seem to exist anymore:
https://ofstack.com/PHP/35753/installing-php-5.5.-15-with-brew-in-an-mac-environment.html

Also, brew install php55 -> Error: No available formula for php55
And brew install php gives the error below that says to contact you.
Thanks!
BaxterZZZ 

apm [05:52 AM] ~$ brew doctor
Your system is ready to brew.
apm [05:54 AM] ~$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew
HEAD: 98505c9a220b2f78278a0a88967d023cafcc6198
Last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: 8-core 64-bit nehalem
OS X: 10.9.5-x86_64
Curl: /usr/local/Library/Homebrew/vendor/portable-curl/current/bin/curl
Xcode: 6.2 => /Volumes/Mav500G/Applications/Xcode.app/Contents/Developer
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: N/A
System Ruby: 2.3.3-222 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.6.0_65-b14-462
apm [05:54 AM] ~$ brew install php
Error: undefined method `livecheck' for Formulary::FormulaNamespace8d205680b76ce25d67c9b7e4787782a5::Php:Class
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/php.rb:10:in `<class:Php>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/php.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Library/Homebrew/formulary.rb:356:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:143:in `<main>'
apm [05:59 AM] ~$ 

apm [05:51 AM] ~$ brew search php
Error: undefined method `livecheck' for Formulary::FormulaNamespace8d205680b76ce25d67c9b7e4787782a5::Php:Class
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/php.rb:10:in `<class:Php>'
/usr/local/Library/Taps/homebrew/homebrew-core/Formula/php.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:77:in `klass'
/usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:168:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:208:in `factory'
/usr/local/Library/Homebrew/cmd/search.rb:142:in `block in search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:141:in `map'
/usr/local/Library/Homebrew/cmd/search.rb:141:in `search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:44:in `search'
/usr/local/Library/brew.rb:143:in `<main>'

**Comment by BaxterZZZ** [comment]
Is Tigerbrew still a live community? Should I be using macports or phpbrew instead?

**Comment by mistydemeo** [comment]
How did you get that `homebrew-core/Formula/php.rb` file? It's not from Tigerbrew.

**Comment by BaxterZZZ** [comment]
I tried a few brew tap commands. Most of them said "not found" but one of them downloaded some things. It was challenging to get anything started because my machine had issues making the secure connection to github and then had the master root certificate issues, but I finally for openssl 1.0.2j installed and added the new certs so at least that works, and I have a personal key now for github downloads. Even though I installed brew via Tigerbrew, I am not really clear whether it only contacts tigerbrew when I use the brew command or whether it goes to regular homebrew(?) Most importantly, can you suggest a way to get from where I am now to an installed version of php that uses the new OpenSSL 1.0.2j ?  Thanks!

**Comment by BaxterZZZ** [comment]
I am happy to test out any commands that you suggest and most the results!
